### PR TITLE
Cross-platform compatibility

### PR DESCRIPTION
**Pull request by exentio**
I added some preprocessor directives to check if the program is running using Mono, and load the right libraries. It's not the best solution because you can also use Mono on Windows, and it may not work for macOS, but for now, it's working fine. I plan to find a better solution in the future.  
I also removed the "Playing" before the game title because it looked redundant to me

### CODE REVIEW

**Comment by gabehxd** [comment]
Any reason why you changed the net version?

**Comment by gabehxd** [comment]
And we will not support ReiNX

**Comment by gabehxd** [comment]
Switching the actual discord rpc for C# might work, not sure about it though as i don't use MoNo for much

**Comment by exentio** [comment]
The version changed just because I didn't have the latest one installed, it's fine if you revert it back  
ReiNX just works because sysmodules work for any firmware, I put it in the readme because it's a common CFW and the one I use  
There's another branch in my repo on which I tried switching to the C# library. It's unstable, like stuff suddenly disappearing from the rich presence, and it could either be my fault (I didn't put too much effort), or the C# library's, because the cross-platform support is still a work in progress on another branch

**Pull request merged**
